# This is a basic workflow to help you get started with Actions

name: Continuous Integration

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        python-version: '3.7.8'
        
    - name: Python Django Coverage GitHub Action
      uses: dc740/django-coveragepy-github-action@0.9
      with:
        # Application
        django-app: 'MAnime'
        # Minimum allowed code coverage
        minimum-coverage: '50'

    - name: Django Security Check
      uses: victoriadrake/django-security-check@v1.0.0
    
    - run: 'python manage.py runserver'
